fork_ex03: fork_ex03.c
	gcc -o fork_ex03 fork_ex03.c
fork_ex02: fork_ex02.c
	gcc -o fork_ex02 fork_ex02.c
fork_hello: fork_hello.c
	gcc -o fork_hello fork_hello.c
fork_ex: fork_ex.c
	gcc -o fork_ex fork_ex.c
