project:
  type: book

book:
  title: "Operating Systems and Networks SoSe 25 Notes"
  author: "Igor Dimitrov"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - process.qmd
    - memory.qmd
  downloads: ["pdf"]
  page-navigation: true

number-depth: 1

bibliography: references.bib

csl: nature.csl

format:
  html:
    theme: cosmo
    toc-depth: 5
  pdf:
    documentclass: scrreprt
    number-depth: 1



